version: '3.9'

services:
  db:
    container_name: db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  produits:
    image: kalilmainbreach/microservice-kalil:produits.v1
    build: ./produits
    container_name: produit-service
    ports:
      - "5000:4000"
    volumes:
      - /app/node_modules
    depends_on:
      - db

  authentification:
    image: kalilmainbreach/microservice-kalil:auth.v1
    build: ./authentification
    container_name: auth-service
    ports:
      - "5002:4002"
    volumes:
      - /app/node_modules
    depends_on:
      - db

  commande:
    image: kalilmainbreach/microservice-kalil:commande.v1
    build: ./commandes
    container_name: commande-service
    ports:
      - "5001:4001"
    volumes:
      - /app/node_modules
    depends_on:
      - authentification
      - produits
      - db